[test]
levels = ["syntax", "install", "registration", "instantiation", "execution"]
publish = false

[test.workflows]
timeout = 300
cpu = ["!remeshing_gpu"]
gpu = ["remeshing_gpu"]

[test.platforms]
linux = false
macos = false
windows = false
windows_portable = false
linux_gpu = true
windows_gpu = false
windows_portable_gpu = false