[apt]
packages = ["libgl1-mesa-glx", "libglu1-mesa"]

# Linux-specific pypi packages
[target.linux-64.pypi-dependencies]
embreex = "*"

# Windows-specific packages
[target.win-64.pypi-dependencies]
msvc-runtime = "*"
embreex = "*"