[dependencies]
cgal = "*"

[target.linux-64.dependencies]
mesalib = "*"
libglu = "*"
libopengl = "*"
xorg-libxi = "*"
libxkbcommon = "*"


[pypi-dependencies]
numpy = "*"
trimesh = { version = "*", extras = ["easy"] }
pymeshlab = "*"